### ISSUE TITLE
Remove all of my commands

### ISSUE THREAD

**Issue by notanoperator** [rovertdude/EmeraldFreedomMod-Beta#12]
https://github.com/rovertdude/EmeraldFreedomMod-Beta/pull/1
https://github.com/rovertdude/EmeraldFreedomMod-Beta/pull/2
https://github.com/rovertdude/EmeraldFreedomMod-Beta/pull/3
https://github.com/rovertdude/EmeraldFreedomMod-Beta/pull/4
https://github.com/rovertdude/EmeraldFreedomMod-Beta/pull/5
https://github.com/rovertdude/EmeraldFreedomMod-Beta/pull/6
https://github.com/rovertdude/EmeraldFreedomMod-Beta/pull/7
https://github.com/rovertdude/EmeraldFreedomMod-Beta/pull/8
https://github.com/rovertdude/EmeraldFreedomMod-Beta/pull/9
https://github.com/rovertdude/EmeraldFreedomMod-Beta/pull/10
https://github.com/rovertdude/EmeraldFreedomMod-Beta/pull/11

**Comment by rovertdude** [comment]
There is no "copyright" on your commands.

**Comment by notanoperator** [comment]
No fucking shit, I just want my commands removed
